language: cpp
compiler:
  - clang
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-software-properties
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:boost-latest/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-4.8
  - sudo apt-get install -qq libboost1.55-all-dev 
  # We want debug symbols for boost as we install gdb later
  - sudo apt-get install -qq libboost1.55-dbg
  - sudo apt-get install -qq protobuf-compiler libprotobuf-dev libssl-dev exuberant-ctags
  # We need gcc >= 4.8 for some c++11 features
  - sudo apt-get install -qq gcc-4.8
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 40 --slave /usr/bin/g++ g++ /usr/bin/g++-4.8
  - sudo update-alternatives --set gcc /usr/bin/gcc-4.8
  # For faster linking
  - sudo apt-get -y install binutils-gold
  # Install libsodium (note: there is a PPA, could use that too but it seems a bit old)
  - wget http://download.libsodium.org/libsodium/releases/libsodium-1.0.0.tar.gz
  - tar -xzf libsodium-1.0.0.tar.gz
  - pushd libsodium-1.0.0
  - ./configure
  - make
  - sudo make install
  - popd
  # For backtrace reporting
  - sudo apt-get -y install gdb
  # Report versions
  - g++ -v
  - clang -v
  - sudo apt-get install -qq mlocate
  - sudo updatedb
  - sudo locate libboost | grep /lib | grep -e ".a$"

script:
  - set -e
  - scons 
  - ldd ./build/stellard
  # Run unittests (under gdb)
  - | # create gdb script
    echo "set env MALLOC_CHECK_=3" > script.gdb 
    echo "run" >> script.gdb
    echo "backtrace full" >> script.gdb 
    # gdb --help
  - cat script.gdb | gdb --ex 'set print thread-events off' --return-child-result --args ./build/stellard --unittest
  # Run integration tests
  - npm install
  - npm test

notifications:
  email:
    false
  slack:
    secure: eOhSpyT0z9aEg6ArTRXfU33HgbCv8g7L5+RGBs6VMmJAVFIwJ8xaXopyE0YLt0M+iADk80jrw8CeoujEPeCXP41usDQzr481ADOl4cUNIntb9ysx+ZKfSeLo86sc+iq2VAYF0Le3c+WEww3aQEbH46tMVvMhcvzGu03hXXGy8vk=
#  irc:
#    channels:
#      - "chat.freenode.net#stellar-dev"
